<?php

// Generated file. Do not edit by hand. Use update.php in project root.

namespace PHPFUI\ConstantContact\Definition;

/**
 * @property string $image_id Unique identifier for this image. Generated by the server on creation.
 * @property string $url The URL of the image. Each component of the URL must be appropriately encoded to avoid illegal characters.
 */
class ImageDto extends \PHPFUI\ConstantContact\Definition\Base
	{
	protected static array $fields = [
		'image_id' => 'string',
		'url' => 'string',

	];
	}
