<?php

// Generated file. Do not edit by hand. Use update.php in project root.

namespace PHPFUI\ConstantContact\Definition;

/**
 * @property string $campaign_id Unique identifier for the post campaign. Generated by the server on creation. Use this value to reference the post in subsequent requests.
 * @property string $name Campaign name for this post. The value provided on creation is sanitized before saving, so the returned value may not exactly match what was sent.
 * @property array<\PHPFUI\ConstantContact\Definition\ProfilePostDto> $profile_posts The list of per-profile posts that make up this campaign.
 * @property string $scheduled_time The date and time to publish the post, in ISO-8601 format. Only set when <code>status</code> is <code>SCHEDULED</code>.
 * @property string $status The current status of the post. Possible values include: * <ul>
 * <li><code>DRAFT</code> — saved without being scheduled for publication</li>
 * <li><code>SCHEDULED</code> — scheduled for future publication at <code>scheduled_time</code></li>
 * <li><code>EXECUTING</code> — currently being published</li>
 * <li><code>ACTIVE</code> — the post has been published and is active on the social network</li>
 * <li><code>PAUSED</code> — publication has been paused</li>
 * <li><code>SUSPENDED</code> — publication has been suspended</li>
 * <li><code>REMOVED</code> — the post has been removed</li>
 * <li><code>DONE</code> — publication has completed</li>
 * <li><code>ERROR</code> — publication encountered an error</li> * </ul>
 */
class PostDto extends \PHPFUI\ConstantContact\Definition\Base
	{
	protected static array $fields = [
		'campaign_id' => 'string',
		'name' => 'string',
		'profile_posts' => 'array<\PHPFUI\ConstantContact\Definition\ProfilePostDto>',
		'scheduled_time' => 'string',
		'status' => 'string',

	];

	protected static array $requiredFields = [
		'profile_posts',
		'status',

	];
	}
