<?php

// Generated file. Do not edit by hand. Use update.php in project root.

namespace PHPFUI\ConstantContact\Definition;

/**
 * @property array<\PHPFUI\ConstantContact\Definition\ImageDto> $images Images to include in the post. Each image must be accessible via a public URL.
 * @property string $post_content_id Identifier for this post content. Generated by the server on creation. When updating a post, existing profile posts must include their original <code>post_content_id</code> unchanged.
 * @property array<\PHPFUI\ConstantContact\Definition\ProfilePostProfileDto> $profiles The list of profiles to post to. Can be an empty list only when the post is in <code>DRAFT</code> status.
 * @property \PHPFUI\ConstantContact\Definition\Settings $settings Network-specific post settings. If no settings are provided, this field will be omitted in the JSON response. All values are persisted as strings.
Currently, only TikTok has available settings:
<pre>{
  "settings": {
    "tiktok": {
      "disable_comment": "true",
      "disable_duet": "false",
      "disable_stitch": "true",
      "auto_add_music": "false"
    }
  }
}</pre>
 * @property string $text The text/caption content for the post. Whether text is required depends on the target social network. In <code>DRAFT</code> status, this is always optional.
 */
class ProfilePostDto extends \PHPFUI\ConstantContact\Definition\Base
	{
	protected static array $fields = [
		'images' => 'array<\PHPFUI\ConstantContact\Definition\ImageDto>',
		'post_content_id' => 'string',
		'profiles' => 'array<\PHPFUI\ConstantContact\Definition\ProfilePostProfileDto>',
		'settings' => '\PHPFUI\ConstantContact\Definition\Settings',
		'text' => 'string',

	];
	}
