<?php

// Generated file. Do not edit by hand. Use update.php in project root.

namespace PHPFUI\ConstantContact\Definition;

/**
 * @property string $account_username The human-readable username of the account that owns this profile.
 * @property string $campaign_activity_id The campaign activity ID for this post on the specified profile. Generated by the server on creation. When updating a post, existing profile entries should include their original <code>campaign_activity_id</code>.
 * @property string $campaign_activity_status The status of the post activity for this profile.
 * @property \PHPFUI\ConstantContact\DateTime $campaign_activity_status_date The activity's timestamp. For <code>SCHEDULED</code> activities, this is typically the same as the scheduled publish time; otherwise, it is the last-modified timestamp.
 * @property string $campaign_activity_status_message A human-readable message describing the current status of the post activity. Can be a generic Constant Contact message or a specific message reported by the social network.
 * @property string $image_url The URL of the profile's image. This image may become stale and is only refreshed when retrieving profiles with <code>include=accessible</code>.
 * @property string $network The social network this profile belongs to.
 * @property string $network_post_id The social network's reference for this post. Only set when the status is <code>DONE</code>.
 * @property string $post_url The permalink URL to the published post on the social network. Only set when the status is <code>DONE</code>.
 * @property string $profile_id The unique identifier for the profile to post to. Use the <code>profile_id</code> from <code>GET /social/profiles</code>.
 * @property string $profile_name The display name of the profile.
 */
class ProfilePostProfileDto extends \PHPFUI\ConstantContact\Definition\Base
	{
	protected static array $fields = [
		'account_username' => 'string',
		'campaign_activity_id' => 'string',
		'campaign_activity_status' => 'string',
		'campaign_activity_status_date' => '\PHPFUI\ConstantContact\DateTime',
		'campaign_activity_status_message' => 'string',
		'image_url' => 'string',
		'network' => 'string',
		'network_post_id' => 'string',
		'post_url' => 'string',
		'profile_id' => 'string',
		'profile_name' => 'string',

	];
	}
