<?php

// Generated file. Do not edit by hand. Use update.php in project root.

namespace PHPFUI\ConstantContact\Definition;

/**
 * @property string $profile_id The profile id this source is associated with. This may be <code>null</code> if this source has not been published yet.
 * @property string $profile_post_id The profile post id this source is associated with. This may be <code>null</code> if this source has not been published yet.
 * @property string $source The source type indicating where the video is hosted. Values include the social network name (e.g. <code>facebook</code>, <code>instagram</code>, <code>linkedin</code>, <code>tiktok</code>) for published videos, <code>s3</code> for pending uploads, or <code>public</code> for publicly accessible URLs.
 * @property string $thumbnail_url The URL of a thumbnail image for the video, if available.
 * @property string $video_source_id The unique (database) id for this object. It should only ever be <code>null</code> for an un-saved object. It is automatically generated by the database, and should be considered read-only. When re-saving a video post, any <code>VideoSourceDto</code> objects should include their original <code>videoSourceId</code>.
 * @property string $video_url The URL of the video source. Unless the <code>source</code> is <code>public</code>, this should only be set by the back-end.
 */
class VideoSourceDto extends \PHPFUI\ConstantContact\Definition\Base
	{
	protected static array $fields = [
		'profile_id' => 'string',
		'profile_post_id' => 'string',
		'source' => 'string',
		'thumbnail_url' => 'string',
		'video_source_id' => 'string',
		'video_url' => 'string',

	];
	}
