---
swagger: "2.0"
info:
  description: "The Constant Contact, Inc. V3 public API, for building integrations\
    \ with Constant Contact, the leading small-business email marketing platform."
  version: "3.0.0"
  title: "AppConnect V3"
  contact:
    name: "webservices@constantcontact.com"
  license:
    name: "Private"
host: "api.cc.email"
basePath: "/v3"
tags:
- name: "Account Services"
  description: "Use the account endpoints and methods to get account information."
- name: "Access Token Information"
  description: "Get authentication information about your access token."
- name: "Bulk Activities"
  description: "Bulk activities endpoints are used to manage large numbers of contacts,\
    \ lists, and tags."
- name: "Contacts"
  description: "Endpoints and methods to get, create, delete, and update one or more\
    \ contacts."
- name: "Contact Lists"
  description: "Endpoints and methods to get, create, delete, and update one or more\
    \ contact lists."
- name: "Contact Tags"
  description: "Endpoints and methods to get, create, delete, and update one or more\
    \ contact tags."
- name: "Contacts Reporting"
  description: "Contact reporting endpoints are used to gather activity reports for\
    \ campaigns sent to a contact."
- name: "Contacts Custom Fields"
  description: "Endpoints and methods to get, create, delete, and update on one or\
    \ more custom fields."
- name: "Email Campaigns"
  description: "Use email campaign endpoints and methods to get, create, and update\
    \ email campaigns."
- name: "Email Campaigns AB Tests"
  description: "Use Email Campaigns A/B Test endpoints and methods to get, create,\
    \ delete and update A/B tests."
- name: "Email Reporting"
  description: "Use the email reporting endpoints and methods to get reporting data\
    \ for email campaigns you sent to contacts."
- name: "Email Scheduling"
  description: "Use email scheduling endpoints and methods to schedule an email campaign\
    \ activity, unschedule an email campaign activity, and GET schedule information."
- name: "Segments"
  description: "Use segments to target a subset of your contacts that are most likely\
    \ to engage with a particular campaign."
- name: "Technology Partners"
  description: "Use partner endpoints to manage client Constant Contact accounts under\
    \ your partner account."
- name: "Technology Partners Webhooks"
  description: "Use partner webhooks to subscribe to billing event notifications from\
    \ Constant Contact."
- name: "My Library"
  description: "Use the MyLibrary methods to manage images in a Constant Contact account"
schemes:
- "https"
paths:
  /account/user/privileges:
    get:
      tags:
      - "Account Services"
      summary: "GET User Privileges"
      description: "Use this method to return the user privileges associated with\
        \ your access token as an array of objects. This method returns all user privileges,\
        \ including privileges the V3 API does not currently use. Constant Contact\
        \ requires specific user privileges to make requests using the V3 API. For\
        \ more information, see the [User Privileges and Roles Overview](/api_guide/user_privileges.html)."
      operationId: "getUserPrivileges"
      security:
      - oauth2_implicit: []
      - oauth2_access_code: []
      - api_key: []
  /account/summary:
    get:
      tags:
      - "Account Services"
      summary: "GET a Summary of Account Details"
      description: "Get account related details for a Constant Contact user account.\
        \ Use the `extra_fields` query parameter to include the `company_logo` and/or\
        \ `physical_address` details in the response body. For more details, see [Get\
        \ Account Summary Details](/api_guide/account_details_get.html)."
      operationId: "getAccountById"
      security:
      - oauth2_implicit:
        - "account_read"
      - oauth2_access_code:
        - "account_read"
      - api_key: []
      x-authorization-privileges:
      - "account:read"
    put:
      tags:
      - "Account Services"
      summary: "PUT (update) Account Details"
      description: "Use this method to update account details for a Constant Contact\
        \ account, such as the email address or phone number. This PUT method provides\
        \ a partial update where only valid properties that you include in the request\
        \ body are updated and excluded properties are not overwritten. For more details,\
        \ see [Put (update) Account Summary Details](/api_guide/account_details_put.html)."
      operationId: "putCustomerById"
      security:
      - oauth2_implicit:
        - "account_update"
      - oauth2_access_code:
        - "account_update"
      - api_key: []
      x-authorization-privileges:
      - "account:update"
  /account/summary/physical_address:
    get:
      tags:
      - "Account Services"
      summary: "GET the Physical Address for the Account"
      description: "Use this method to get the address where the account's organization\
        \ physically resides. The physical address is required to send emails and\
        \ displays on the footer of every email that is sent from the account."
      operationId: "getPhysicalAddress"
      security:
      - oauth2_implicit:
        - "account_read"
      - oauth2_access_code:
        - "account_read"
      - api_key: []
      x-authorization-privileges:
      - "account:read"
    put:
      tags:
      - "Account Services"
      summary: "PUT (update) the Physical Address for an Account"
      description: "Use this method to update the organization's physical address\
        \ for the Constant Contact user account. The physical address is required\
        \ to send emails and displays on the footer of every email that is sent from\
        \ the account. To get the current physical address, make a GET call to `/account/summary/physical_address`.\
        \ The country (<code>country_code</code>) where the account organization resides\
        \ determines whether you use the <code>state_code</code> to specify United\
        \ States (<code>US</code>) and Canada (<code>CA</code>) addresses, or use\
        \ the <code>state_name</code> to specify all other countries. For more details,\
        \ see [Put (update) the Physical Address for the Account](/api_guide/account_address_put.html).\
        \ You must have the role of Account Owner assigned to update account level\
        \ details. "
      operationId: "putPhysicalAddress"
      security:
      - oauth2_implicit:
        - "account_update"
      - oauth2_access_code:
        - "account_update"
      - api_key: []
      x-authorization-privileges:
      - "account:update"
  /account/emails:
    get:
      tags:
      - "Account Services"
      summary: "GET a Collection of Account Email Addresses"
      description: "Use this method to return a collection of email addresses for\
        \ the account associated with your access token. When you <a href=\"https://v3.developer.constantcontact.com/api_reference/index.html#!/Email_Campaigns/createEmailCampaignUsingPOST\"\
        \ target=\"_blank\">Create an Email Campaign<a/>, you must use an account\
        \ email address with a `CONFIRMED` status in the email campaign `from_email`\
        \ and `reply_to_email` headers.\n      \n\nUse the query parameters to filter\
        \ results. You can filter using `confirm_status`, `role_code`, or `email_address`.\
        \ For example, searching with `confirm_status=CONFIRMED` returns all confirmed\
        \ email addresses in the account. This method only supports one query parameter\
        \ at a time.\n"
      operationId: "retrieveEmailAddresses"
      security:
      - oauth2_implicit:
        - "account_read"
      - oauth2_access_code:
        - "account_read"
      - api_key: []
      x-authorization-privileges:
      - "account:read"
    post:
      tags:
      - "Account Services"
      summary: "POST Add an Account Email Address"
      description: "Use this method to add a new email address to a Constant Contact\
        \ account. If the email address you are adding already exists in the account\
        \ the API will return a 409 conflict error. \n\nWhen you add a new email address\
        \ to an account, Constant Contact automatically sends an email to that address\
        \ with a link to confirm it. After a user clicks that link, the account email\
        \ status changes from `UNCONFIRMED` to `CONFIRMED`. You can use confirmed\
        \ account email addresses in the email campaign `from_email` and `reply_to_email`\
        \ headers. For more use case information, see [Add an Account Email Address](/api_guide/account_post_emails.html)\
        \ in the API guide. \n"
      operationId: "addAccountEmailAddress"
      security:
      - oauth2_implicit:
        - "account_update"
      - oauth2_access_code:
        - "account_update"
      - api_key: []
      x-authorization-privileges:
      - "account:update"
  /activities:
    get:
      tags:
      - "Bulk Activities"
      summary: "GET Activity Status Collection"
      description: "This endpoint returns a collection of activities. Use the state\
        \ query parameter to include only activities with a specific status (processing,\
        \ completed, cancelled, failed, or time_out). Use the limit query parameter\
        \ to define the number of activities returned per page. Learn [more](/api_guide/activity_status.html)."
      operationId: "getActivityStatusCollection"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/{activity_id}:
    get:
      tags:
      - "Bulk Activities"
      summary: "GET an Activity Status"
      description: "This endpoint returns an activity status report."
      operationId: "getActivity"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/contact_exports:
    post:
      tags:
      - "Bulk Activities"
      summary: "Export Contacts to a File"
      description: "Use this method to create an activity that exports contacts and\
        \ contact details to a CSV file. By default, all contacts are exported. To\
        \ filter contacts to export, specify the source to use, `contact_id`, `list_id`,\
        \ or `segment_id` (all mutually exclusive).\nBy default, all contact related\
        \ fields are exported. Use the fields array to only export specific contact\
        \ fields. You must export `email_address` to successfully export `email_optin_source`,\
        \ `email_optin_date`, `email_optout_source`, `email_optout_date`, or `email_optout_reason`.\n\
        After Constant Contact finishes processing the activity, use the `results`\
        \ link in the response body to retrieve the CSV file."
      operationId: "postContactsExport"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/contact_delete:
    post:
      tags:
      - "Bulk Activities"
      summary: "Delete Contacts in Bulk"
      description: "Use this endpoint to bulk delete contacts in an account. Contacts\
        \ to delete are specified by contact_id (up to 500), or by list_id (up to\
        \ 50 lists); all contacts that are members of the list_ids are deleted. Deleted\
        \ contacts won’t receive email from you, and they don’t count as active contacts.\
        \ Unlike unsubscribed contacts, deleted contacts can be added back to an account.\
        \ [Learn how to revive deleted contacts](/api_guide/contacts_delete.html#revive)."
      operationId: "postContactDelete"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/contacts_file_import:
    post:
      tags:
      - "Bulk Activities"
      summary: "Import Contacts using a CSV File"
      description: "This multipart method creates an asynchronous background job that\
        \ adds or updates contacts by importing a CSV file containing contact information.\
        \ Do not use a Content-Type header value with this method.\n\nImporting a\
        \ new contact automatically sets the contact's `permission_to_send` property\
        \ as `implicit` and the `opt_in_source` property as `Account`. Importing an\
        \ existing contact only updates the contact properties you include in the\
        \ request.\n\nThe CSV file has a maximum of 40,000 lines including the header\
        \ row (39,999 contacts) and a maximum file size of 4 megabytes (MB).  Lines\
        \ above the 40,000 line maximum are not processed. If the request body exceeds\
        \ 4 MB, only the contacts contained in the first 4 MB are imported and the\
        \ remaining data is dropped."
      operationId: "contactsCSVImport"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/contacts_json_import:
    post:
      tags:
      - "Bulk Activities"
      summary: "Import Contacts using a JSON Payload"
      description: "Use this method to create an asynchronous background job that\
        \ adds new contacts or updates existing contacts by importing a JSON payload.\
        \ This method requires a request body that contains the contact data you are\
        \ importing and the contact lists you are adding all imported contacts to.\n\
        \nImporting a new contact automatically sets the contact's `permission_to_send`\
        \ property as `implicit` and the `opt_in_source` property as `Account`. Importing\
        \ an existing contact only updates the contact properties you include in the\
        \ request.\n\nYou can import custom fields by prefixing a custom field name\
        \ with `cf:` and adding it as a contact property. For example, use the property\
        \ name `cf:first_name` if you have a custom field named first_name. The custom\
        \ field must already exist in the Constant Contact account you are using.\
        \ Each contact can contain up to 25 custom fields.\n\nThe request body payload\
        \ has a maximum size of 4 megabytes (MB). If the request body exceeds 4 MB,\
        \ this method only imports the first 4 MB and drops the remaining data."
      operationId: "bulkImportContactsJSON"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/remove_list_memberships:
    post:
      tags:
      - "Bulk Activities"
      summary: "Remove Contacts from Lists"
      description: "Use this method to create an activity that removes contacts from\
        \ one or more lists. Use the properties in the `source` object to remove specific\
        \ contacts from your targeted lists. Use the `list_ids` array to specify the\
        \ lists from which you want to remove the source contacts.\n"
      operationId: "postListRemoveContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/add_list_memberships:
    post:
      tags:
      - "Bulk Activities"
      summary: "Add Contacts to Lists"
      description: "Use this method to create an activity that adds contacts to one\
        \ or more lists. Each contact can be a member of up to 50 lists. Use the properties\
        \ in the `source` object to specify the contacts you want to add to lists.\
        \ Use the `list_ids` array to specify which lists you want to add your source\
        \ contacts to."
      operationId: "postListAddContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/contacts_taggings_remove:
    post:
      tags:
      - "Bulk Activities"
      summary: "Remove Tags from Contacts"
      description: "Use this method to create an asynchronous activity that removes\
        \ one or more tags from all contacts meeting your contact filtering criteria.\
        \ Filtering criteria must include the `source` type used to identify contacts\
        \ from which the specified tags (`tag_id`) are removed.\n\nSource types are\
        \ mutually exclusive. If the specified source is either `all_active_contacts`\
        \ or `list_ids`, you can optionally choose to `exclude` specified contacts\
        \ by `contact_id`. Use the activity link in the results to check the status\
        \ of your request.\"\n\nFor more use case information, see \"[Remove Tags\
        \ from Contacts](/api_guide/remove_tagging_activity.html)\"\n"
      operationId: "postTagRemoveContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/contacts_taggings_add:
    post:
      tags:
      - "Bulk Activities"
      summary: "Add Tags to Contacts"
      description: "Use this method to create an asynchronous activity that adds one\
        \ or more tags to all contacts meeting your contact filtering criteria. Use\
        \ the `source` type to identify contacts from which the specified tags (`tag_id`)\
        \ are added.\n\nSource criteria are mutually exclusive. If the source is `all_active_contacts`\
        \ or `list_ids`, you can optionally choose to `exclude` contacts by `contact_id`.\
        \ Use the activity link in the results to check the status of your request.\n\
        \nFor more use case information, see \"[Add Tags to Contacts](/api_guide/add_tagging_activity.html)\"\
        \n"
      operationId: "postTagAddContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /activities/contacts_tags_delete:
    post:
      tags:
      - "Bulk Activities"
      summary: "Delete Tags"
      description: "Use this method to create an asynchronous activity that deletes\
        \ up to 500 tags. Deleted tags are automatically removed from tagged contacts.\
        \ Use the `tag_ids` array of string values in the request body to specify\
        \ which tags to delete."
      operationId: "postTagDelete"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /segments:
    get:
      tags:
      - "Segments"
      summary: "GET all Segments"
      description: "Use this method to get a list of all segments associated with\
        \ the account. You can sort segment results and limit the number of segments\
        \ that display per page. Deleted segments are excluded from the results. For\
        \ more use case information, see [Get All Segments](/api_guide/segment_get_all.html)\
        \ in the API guide."
      operationId: "getAccountSegments"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:read"
    post:
      tags:
      - "Segments"
      summary: "POST (create) a Segment"
      description: "Use this method to create a new segment. You create segments to\
        \ target a subset of your contacts that meet your specific criteria for a\
        \ marketing campaign. The segment `name` must be unique. The `segment_criteria`\
        \ requires single-string escaped JSON. Constant Contact uses the contact data\
        \ that you specify in the `segment_criteria` to evaluate and identify the\
        \ contacts you want to target. Contact data can be grouped from different\
        \ data sources, including:\n\n  -  **`tracking`**: Supports **or** and **and**\
        \ groups.\n\n\n  -  **`contact`**: Supports **or** and **and** groups.\n\n\
        \n  -  **`list_membership`**: Supports **or** groups.\n\n  -  **`tags`**:\
        \ Supports **or** groups.\n\nIf you do not specify `list_membership` as criteria,\
        \ Constant Contact evaluates all contacts in your account. To avoid returning\
        \ a 400 error response, when specifying the `segment_criteria` do not request\
        \ more than 500 email campaigns or a date range greater than 1825 days (5\
        \ years) be evaluated.\n\nFor more use case information, see the [Segments\
        \ Overview](/api_guide/segments_overview.html) in the API guide."
      operationId: "createSegment"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:write"
  /segments/{segment_id}:
    get:
      tags:
      - "Segments"
      summary: "GET a Segment's Details"
      description: "Use this method to get details about a segment, including the\
        \ segment criteria. If you know the `segment_id` You can also use this method\
        \ to get details about a deleted segment. For more use case information, see\
        \ [Get a Segment's Details](/api_guide/segment_get.html) in the API guide."
      operationId: "getSegmentDetail"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:read"
    put:
      tags:
      - "Segments"
      summary: "PUT (update) a Segment"
      description: "Use this method to update an existing segment's name (`name`)\
        \ and/or contact selection criteria (`segment_criteria`). You must specify\
        \ both the `name` and the `segment_criteria` in the request body, even if\
        \ you don't plan to update both. The segment's name must be unique and the\
        \ JSON must be valid (requires single-string escaped JSON). To avoid returning\
        \ a 400 error response, when specifying the `segment_criteria` do not request\
        \ more than 500 email campaigns or a date range greater than 1825 days (5\
        \ years) be evaluated. For more use case information, see [Update Segment\
        \ Details](/api_guide/segment_update.html) in the API guide."
      operationId: "updateSegment"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:write"
    delete:
      tags:
      - "Segments"
      summary: "DELETE a Segment"
      description: "Use this method to delete a segment from your account. Before\
        \ deleting a segment, verify that the segment is not associated with a scheduled\
        \ campaign.\n\nDeleted segments do not display in the results when using the\
        \ `GET /segments` endpoint. If you know the `segment_id`, you can use the\
        \ `GET /segments/{segment_id}` endpoint to view the deleted segment's details.\
        \ A segment's details are preserved for external reference purposes, such\
        \ as displaying the segment name in a campaign's history. For more use case\
        \ information, see [Delete a Segment](/api_guide/segment_delete.html) in the\
        \ API guide."
      operationId: "deleteSegment"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:write"
  /segments/{segment_id}/name:
    patch:
      tags:
      - "Segments"
      summary: "PATCH (rename) a Segment"
      description: "Use this method to update an existing segment `name` with a new\
        \ unique name in the request body. For more use case information, see [Rename\
        \ a Segment](/api_guide/segment_rename.html) in the API guide."
      operationId: "updateSegmentName"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:write"
  /contacts/{contact_id}:
    get:
      tags:
      - "Contacts"
      summary: "GET a Contact"
      description: "This endpoint GETs a specific contact resource (contact_id). Use\
        \ the `include` query parameter to add any of the available contact sub-resources\
        \ to the response payload."
      operationId: "getContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:read"
    put:
      tags:
      - "Contacts"
      summary: "PUT (update) a Contact"
      description: "The PUT method updates an existing contact. You must include the\
        \ `update_source` property in the PUT request payload. To restore  a deleted\
        \ contact you must specify the `update_source` as `Account`. When updating\
        \ any resource using PUT, all properties are updated, overwriting all previous\
        \ values. Any properties left blank or not included in the request are overwritten\
        \ with null value - however this does not apply to contact subresources. Add\
        \ or change any of the subresources by including them in the PUT request payload.\
        \ Omitted subresources are not overwritten with null. If the contact being\
        \ updated is deleted, the contact will be revived."
      operationId: "putContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
    delete:
      tags:
      - "Contacts"
      summary: "DELETE a Contact"
      description: "Deletes the contact identified by the contact_id path parameter.\
        \ Deleted contacts won't receive email from you, and they don't count as active\
        \ contacts. Unlike unsubscribed contacts, deleted contacts can be revived,\
        \ or added back to an account. Learn how to [revive deleted contacts](/api_guide/contacts_delete.html#revive)."
      operationId: "deleteContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /contacts:
    get:
      tags:
      - "Contacts"
      summary: "GET Contacts Collection"
      description: "Use this method to return a collection of contacts. Use the query\
        \ parameters to search for contacts that match specific criteria. For example,\
        \ you can search by the contact's `email` address, `status`, `lists` memberships,\
        \ `segment_id`, `tags`, `notes` and `updated_after` date. Use the `limit`\
        \ query parameter to limit the number of results returned per page. Use the\
        \ `include` query parameter to include contact sub-resources in the response\
        \ and `include_count` to include the total number of contacts that meet your\
        \ specified search criteria.\n\nBy default, this method returns all contacts\
        \ that are not deleted. Use the `status` query parameter with the value `all`\
        \ to return all contacts including deleted contacts."
      operationId: "getContacts"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:read"
    post:
      tags:
      - "Contacts"
      summary: "POST (create) a Contact"
      description: "Creates a new contact resource; you must include the `create_source`\
        \ property and at least one of the following properties when creating a new\
        \ contact: `first_name`, `last_name`, or `email_address` (`email_address`\
        \ must be unique for each contact)."
      operationId: "createContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /contacts/sign_up_form:
    post:
      tags:
      - "Contacts"
      summary: "Create or Update a Contact"
      description: "Use this method to create a new contact or update an existing\
        \ contact. This method uses the `email_address` string value you include in\
        \ the request body to determine if it should create an new contact or update\
        \ an existing contact.\n\nUpdates to existing contacts are partial updates.\
        \ This method only updates the contact properties you include in the request\
        \ body. Updates append new contact lists or custom fields to the existing\
        \ `list_memberships` or `custom_fields` arrays.\n<div class=\"Msg\"><p class=\"\
        note-text\">Only use this method when a contact gives you their explicit permission\
        \ to send them emails. It is a violation of US and Canadian anti-spam laws,\
        \ as well as a serious violation of the Constant Contact Terms of Service\
        \ to use the Opt-in features of the API to opt a contact back in without his\
        \ or her own action and consent.</p></div>\n\nWhen this method creates a new\
        \ contact, it returns a 201 response code.\n\nWhen this method updates an\
        \ existing contact, it returns a 200 response code. Updating a deleted contact\
        \ restores the contact.\n\nThe method automatically modifies the contact's\
        \ `permission_to_send` and `opt_in_source` properties depending on the [Confirmed\
        \ Opt-In](https://knowledgebase.constantcontact.com/articles/KnowledgeBase/5533-obtain-permission-to-send-email-campaigns-to-your-contacts-by-using-confirmed-opt-in)\
        \ Constant Contact account setting:\n\nIf Confirmed Opt-in is _enabled_, this\
        \ method automatically sets the `permission_to_send` property as pending\\\
        _confirmation for new contacts. \n\nIf Confirmed Opt-in is _disabled_, this\
        \ method automatically sets the `permission_to_send` property as explicit\
        \ and the `opt_in_source` property as `Contact` for new contacts. Updated\
        \ contacts have their `permission_to_send` property set as explicit.\n   \
        \   \n"
      operationId: "createOrUpdateContact"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /contacts/contact_id_xrefs:
    get:
      tags:
      - "Contacts"
      summary: "GET a collection of V2 and V3 API contact IDs"
      description: "<div class=\"Msg Msg--warning\"><p class=\"note-text\">Use this\
        \ endpoint to migrate your locally stored V2 contact ids to the new V3 format.\
        \ Developers are expected to use this endpoint sparingly. This endpoint is\
        \ NOT intended for regular or repeated use. Constant Contact will eventually\
        \ deprecate and remove this endpoint.</p></div>\n\nThis GET call retrieves\
        \ a collection of cross-referenced contact sequence IDs (`id` used in the\
        \ V2 API) and UUIDs (`contact_id` used in the V3 API). This endpoint is intended\
        \ for developers who have an existing V2 API integration, and are migrating\
        \ their users to a new V3 API integration. The V2 and V3 APIs use different\
        \ resource ID formats. Use the `sequence_ids` query parameter to specify a\
        \ set of comma delimited V2 contacts ids to cross-referenced with their V3\
        \ `contact_ids`. See [Migrating to V3](/api_guide/migration_overview.html)\
        \ to learn more.\n"
      operationId: "getContactIdXrefs"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:read"
  /contact_custom_fields/{custom_field_id}:
    get:
      tags:
      - "Contacts Custom Fields"
      summary: "GET a custom_field"
      description: "This GET call retrieves a `custom_field` resource, specified by\
        \ `custom_field_id`."
      operationId: "getCustomField"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:read"
    put:
      tags:
      - "Contacts Custom Fields"
      summary: "PUT (update) a custom_field"
      description: "This PUT request updates an existing `custom_field` object."
      operationId: "putCustomField"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
    delete:
      tags:
      - "Contacts Custom Fields"
      summary: "DELETE a custom_field"
      description: "This DELETE request deletes a custom_field from the user's account"
      operationId: "deleteCustomField"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /contact_custom_fields:
    get:
      tags:
      - "Contacts Custom Fields"
      summary: "GET custom_fields Collection"
      description: "This GET request returns all `custom_fields` defined in the user's\
        \ account.\n<div class=\"Msg\"><p class=\"note-text\">This method does not\
        \ currently support filtering results using the custom field update date.</p></div>\n"
      operationId: "getCustomFields"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:read"
    post:
      tags:
      - "Contacts Custom Fields"
      summary: "POST (create) a custom_field"
      description: "This POST request adds a new `custom_field` to the user's account.\
        \ A user can configure up to 100 `custom_fields` in their account."
      operationId: "postCustomFields"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /contact_lists/{list_id}:
    get:
      tags:
      - "Contact Lists"
      summary: "GET a List"
      description: "Use this method to get details about a specific contact list (`list_id`)."
      operationId: "getList"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:read"
    put:
      tags:
      - "Contact Lists"
      summary: "PUT (update) a List"
      description: "Updates an existing contact list resource, specified by `list_id`"
      operationId: "putList"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:write"
    delete:
      tags:
      - "Contact Lists"
      summary: "DELETE a List"
      description: "Deletes the specified contact list and its membership. DELETE\
        \ List requests are processed asynchronously, and you can track the status\
        \ of the request by making a GET call to the URI shown in the `_links` property\
        \ in the response."
      operationId: "deleteListActivity"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:write"
  /contact_lists:
    get:
      tags:
      - "Contact Lists"
      summary: "GET Lists Collection"
      description: "Use this method to return details about all contact lists for\
        \ the account.\n<div class=\"Msg\"><p class=\"note-text\">This method does\
        \ not currently support filtering results using the contact list update date.</p></div>\n"
      operationId: "getLists"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:read"
    post:
      tags:
      - "Contact Lists"
      summary: "POST (create) a List"
      description: "Create a new contact list resource"
      operationId: "createList"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:write"
  /contact_lists/list_id_xrefs:
    get:
      tags:
      - "Contact Lists"
      summary: "GET a collection of V2 and V3 API List IDs"
      description: "<div class=\"Msg Msg--warning\"><p class=\"note-text\">Use this\
        \ endpoint to migrate your locally stored V2 contact list data to the new\
        \ V3 format. Developers are expected to use this endpoint sparingly. This\
        \ endpoint is NOT intended for regular or repeated use. Constant Contact will\
        \ eventually deprecate and remove this endpoint.</p></div>\n\nThis GET call\
        \ retrieves a collection of cross-referenced list sequence IDs (`id` used\
        \ in the V2 API) and UUIDs (`list_id` used in the V3 API). This endpoint is\
        \ intended for developers who have an existing V2 API integration, and are\
        \ migrating their users to a new V3 API integration. The V2 and V3 APIs use\
        \ different resource ID formats. Use the `sequence_ids` query parameter to\
        \ specify a set of comma delimited V2 list ids to cross-reference. See [Migrating\
        \ Apps and Data to V3](/api_guide/migration_overview.html) to learn more.\"\
        \ \n"
      operationId: "getListIdXrefs"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:lists:read"
  /contact_tags/{tag_id}:
    get:
      tags:
      - "Contact Tags"
      summary: "GET Tag Details"
      description: "Use this method to get tag details for a specified `tag_id`. Use\
        \ the `include_count` query parameter to include or exclude the total number\
        \ of contacts to which this tag is assigned. To learn more, see  [Get a Tag's\
        \ Details](/api_guide/tags_get_single.html)."
      operationId: "getTag"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:read"
    put:
      tags:
      - "Contact Tags"
      summary: "PUT (Update) a Tag"
      description: "Use this method to rename an existing tag to a new unique tag\
        \ name (`name`). The maximum length is 255 characters. The `tag_source` value\
        \ cannot be updated using this method. You can set the `tag_source` value\
        \ using the `POST contact_tags method`. [Learn more](/api_guide/tags_update.html)"
      operationId: "putTag"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
    delete:
      tags:
      - "Contact Tags"
      summary: "DELETE a Tag"
      description: "Use this method to create an activity used to un-assign a tag\
        \ from all assigned contacts and delete the tag. This is an asynchronous activity.\
        \ To view activity details for the delete request, use the href link returned\
        \ in the response. [Learn more](/api_guide/tags_delete.html)."
      operationId: "deleteTag"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /contact_tags:
    get:
      tags:
      - "Contact Tags"
      summary: "GET Details for All Tags"
      description: "Use this endpoint to get details for all tags in your account.\
        \ Use the <code>include_count</code> query parameter to include the total\
        \ number of contacts assigned each tag. Use the <code>limit</code> query parameter\
        \ to limit the number of tag results returned per page. To get the next page\
        \ of results, copy the <code>cursor={the cursor ID}</code> from the resulting\
        \ href link and add it (<code>&</code>) to the URL. For example:\n\n<p><code>/v3/contact_tags?limit=1&cursor=</code></p><p><code>bGltaXQ9MSZuZXh0PTJjZDgwMjdhLTc4YzAtMTFlOS1iZmQwLWZhMTYzZTZiMDFjMQ=</code></p>\n\
        To learn more, see [Get Tags](/api_guide/tags_get.html)."
      operationId: "getTags"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:read"
    post:
      tags:
      - "Contact Tags"
      summary: "POST (Create) a Tag"
      description: "Use this method to create a new tag. The tag `name` is required\
        \ and must be unique and can include most common keyboard symbols. Optionally,\
        \ when creating a new tag you can specify the source (`tag_source`) used to\
        \ identify the contacts to tag in the request body. [Learn more](/api_guide/tags_create.html)."
      operationId: "postTag"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "contacts:write"
  /emails:
    get:
      tags:
      - "Email Campaigns"
      summary: "GET a Collection of Email Campaigns"
      description: "Use this method to list and get details about your email campaigns.\
        \ By default, this method returns all email campaigns for the user account\
        \ including deleted email campaigns. To get email campaigns within a date-range,\
        \ use the `after_date` and `before_date` query parameters.\n\nThis endpoint\
        \ does not return campaign activity details for each email campaign in the\
        \ collection. To get email campaign activity details for a single email campaign,\
        \ use the GET `/emails/{campaign_id}` endpoint.\"\n<div class=\"Msg\"><p class=\"\
        note-text\">This method does not currently support filtering results using\
        \ the email campaign creation date.</p></div>\n"
      operationId: "retrieveEmailCampaignsUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
    post:
      tags:
      - "Email Campaigns"
      summary: "POST (Create) a New Email Campaign"
      description: "Use this method to create a new email campaign. This method also\
        \ creates new `primary_email` and `permalink` email campaign activities and\
        \ associates them with the new email campaign.\n\nThe request body must contain\
        \ the `name` property and the `email_campaign_activities` array. The `email_campaign_activities`\
        \ array contains the main content of your email campaign using the required\
        \ properties `format_type`, `from_name`, `from_email`, `reply_to_email`, `subject`,\
        \ and `html_content`.\n"
      operationId: "createEmailCampaignUsingPOST"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:write"
  /emails/{campaign_id}:
    get:
      tags:
      - "Email Campaigns"
      summary: "GET Details About a Single Email Campaign"
      description: "Use this method to get details about a single email campaign and\
        \ campaign related activities. Details include the email campaign name, current\
        \ status, create date, last update date, and a list of campaign activities;\
        \ including the `campaign_activity_id` and `role`."
      operationId: "retrieveEmailCampaignUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
    delete:
      tags:
      - "Email Campaigns"
      summary: "DELETE an Email Campaign"
      description: "Use this method to delete an email campaign and the email campaign\
        \ activities associated with the email campaign. You cannot delete an email\
        \ campaign when it has a `Scheduled` status.\n\nConstant Contact users can\
        \ restore deleted email campaigns using the UI.\n"
      operationId: "removeEmailCampaignUsingDELETE"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:delete"
    patch:
      tags:
      - "Email Campaigns"
      summary: "PATCH (Update) an Email Campaign Name"
      description: "Use this method to rename an email campaign. The name is not visible\
        \ to contacts. The name must be unique and cannot exceed 80 characters. You\
        \ cannot rename email campaigns that have a `Removed` status."
      operationId: "renameEmailCampaignUsingPATCH"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:write"
  /emails/campaign_id_xrefs:
    get:
      tags:
      - "Email Campaigns"
      summary: "GET a Collection of V2 and V3 API Email Campaign Identifiers"
      description: "<div class=\"Msg Msg--warning\"><p class=\"note-text\">Use this\
        \ endpoint to migrate your locally stored V2 email campaign data to the new\
        \ V3 format. Developers are expected to use this endpoint sparingly. This\
        \ endpoint is NOT intended for regular or repeated use. Constant Contact will\
        \ eventually deprecate and remove this endpoint.</p></div>\n\nUse this method\
        \ to migrate your local V2 API email data to the V3 API format. For each value\
        \ that you provide in the `v2_email_campaign_ids` query parameter, this method\
        \ returns the corresponding V3 `campaign_id` and V3 `campaign_activity_id`\
        \ UUID value. For more information on the changes to the email campaign resource\
        \ model, see [V3 Email Campaign Resource Changes](/api_guide/v3_v2_email_campaign_deltas.html)\
        \ in the API guide.\n"
      operationId: "retrieveXrefMappingsUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
  /emails/activities/{campaign_activity_id}:
    get:
      tags:
      - "Email Campaigns"
      summary: "GET a Single Email Campaign Activity"
      description: "Use this method to return a specific email campaign activity.\
        \ Each email campaign activity contains the email content, metadata, and styling\
        \ information of an email. Email campaign activities can also contain either\
        \ contact lists or segments. Constant Contact uses this information to determine\
        \ who to send the email campaign activity to when you schedule it. You cannot\
        \ get email campaign activities that have a `REMOVED` status.\n"
      operationId: "retrieveEmailCampaignActivityUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
    put:
      tags:
      - "Email Campaigns"
      summary: "PUT (Update) An Email Campaign Activity"
      description: "Use this method to update an email campaign activity by including\
        \ the complete email campaign activity with your changes in the request body.\
        \ The request body requires the `from_name`, `from_email`, `reply_to_email`,\
        \ and `subject` properties.\n\nYou can only update email campaign activities\
        \ that have the `primary_email` role and that are in `DRAFT` or `Done` status.\n\
        When you use a PUT method to update a resource, the V3 API overwrites any\
        \ properties that are missing in the request body. However, the V3 API does\
        \ not overwrite subresources that you omit in the request body or missing\
        \ properties in subresources. This method considers `physical_address_in_footer`,\
        \ `document_properties`, `html_content`, and `permalink_url` subresources\
        \ of the email campaign activity.\n"
      operationId: "updateEmailCampaignActivityUsingPUT"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:write"
  /emails/activities/{campaign_activity_id}/schedules:
    get:
      tags:
      - "Email Scheduling"
      summary: "GET an Email Campaign Activity Schedule"
      description: "Use this method to return the current schedule for an email campaign\
        \ activity. This schedule contains the date that Constant Contact will send\
        \ the email campaign activity to contacts. If the email campaign activity\
        \ is not in `SCHEDULED` status, this method returns an empty array and a 200\
        \ response code."
      operationId: "retrieveEmailSchedulesUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
    post:
      tags:
      - "Email Scheduling"
      summary: "POST (Create) an Email Campaign Activity Schedule"
      description: "Use this method to schedule when Constant Contact will send an\
        \ email campaign activity to contacts. Use the `scheduled_date` request body\
        \ property to enter the ISO-8601 format date that you want Constant Contact\
        \ to send the email campaign activity on. \n\nBefore you schedule an email\
        \ campaign activity, you must update the email campaign activity and specify\
        \ which contacts you want Constant Contact to send the email to. When you\
        \ make a PUT call to update an email campaign activity, use the `contact_list_ids`\
        \ or `segment_ids` array to add contacts.\n\nYou can only schedule email campaign\
        \ activities that have the `primary_email` role and are in `DRAFT`, `DONE`,\
        \ or `ERROR` status. When you schedule an email campaign activity in `DONE`\
        \ status, Constant Contact does not send the email campaign activity to contacts\
        \ that already received it. Constant Contact only sends the email campaign\
        \ activity to any new contacts in the contact lists or segment you use.\n"
      operationId: "scheduleEmailCampaignActivityUsingPOST"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:send"
    delete:
      tags:
      - "Email Scheduling"
      summary: "DELETE an Email Campaign Activity Schedule"
      description: "Use this method to unschedule an email campaign activity by deleting\
        \ the schedule. You can only unschedule email campaign activities that are\
        \ in `SCHEDULED` status. Unscheduling reverts the email campaign activity\
        \ to the status prior to `SCHEDULED`."
      operationId: "unscheduleEmailCampaignActivityUsingDELETE"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:send"
  /emails/activities/{campaign_activity_id}/tests:
    post:
      tags:
      - "Email Scheduling"
      summary: "POST Test Send an Email Campaign Activity"
      description: "Use this method to send a test email to specific email addresses.\
        \ Test emails allow you to verify how the email campaign activity will look\
        \ before you send it to contacts. This method uses the `email_addresses` array\
        \ in the request body to determine the recipients of the test email. The test\
        \ email does not process any dynamic content in the email campaign activity.\
        \ Dynamic content includes contact and custom field variables.\n\nYou can\
        \ send up to 50 test emails each day. Each recipient you add to the `email_addresses`\
        \ array in the request body counts towards this limit. Successfully sending\
        \ a test email returns a 204 response code without a response body.\n"
      operationId: "testSendCampaignActivityUsingPOST"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:send"
  /emails/activities/{campaign_activity_id}/previews:
    get:
      tags:
      - "Email Scheduling"
      summary: "GET the HTML Preview of an Email Campaign Activity"
      description: "Use this method to get the HTML preview of an email campaign activity.\
        \ The HTML preview allows you to verify how the email campaign activity will\
        \ look before you send it to contacts.\n\nCustom code emails (`format_type`\
        \ 5) use the Constant Contact account owner's contact information to process\
        \ contact, custom field, and account variables in the preview.\n\nThis method\
        \ returns the HTML preview encoded as a JSON string. You will need to decode\
        \ the string before you can use it as valid HTML.\n"
      operationId: "retrieveEmailCampaignActivityPreviewUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
  /emails/activities/{campaign_activity_id}/send_history:
    get:
      tags:
      - "Email Scheduling"
      summary: "GET the Send History of an Email Campaign Activity"
      description: "Use this method to return the send history of an email campaign\
        \ activity. This method returns the send history as an array containing an\
        \ object for each time you sent a specific email campaign activity to contacts.\
        \ \n\nEach send history object contains the email campaign activity send date,\
        \ the number of contacts it was sent to, and the contact lists or segments\
        \ used to send it. Each send history object also includes if the send attempt\
        \ completed or encountered an error, and the reason why each error occurred.\
        \ This method returns results in ascending order starting with the first send\
        \ attempt. \n\nIf the email campaign activity has not been sent to contacts,\
        \ this method returns a 200 response and an empty array.\n"
      operationId: "retrieveEmailSendHistoryUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
  /emails/activities/{campaign_activity_id}/non_opener_resends:
    get:
      tags:
      - "Email Campaigns"
      summary: "GET Details for a Resend to Non-openers Campaign Activity"
      description: "Get details about a resend to non-openers campaign activity. If\
        \ resend activity does not exist for the specified `campaign_activity_id`,\
        \ an empty list is returned in the results. You can only create one resend\
        \ activity per email campaign."
      operationId: "retrieveResendToNonOpenersUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
    post:
      tags:
      - "Email Campaigns"
      summary: "POST a Resend to Non-openers Campaign Activity"
      description: "Use this POST method to resend a primary campaign activity to\
        \ contacts that did not open a campaign activity that has a current `status`\
        \ of `Draft`, `Scheduled`, or `Done`. You can only create one resend activity\
        \ per email campaign.\n \n After an email campaign activity is sent to contacts,\
        \ Constant Contact waits the specified number of `delay_days` or `delay_minutes`\
        \ (properties are mutually exclusive) before resending to non-openers. If\
        \ you set both `delay_days` or `delay_minutes`, `delay_minutes` is ignored\
        \ in the request. You can resend to non-openers a minimum of twelve hours\
        \ (720 minutes) and a maximum of up to 10 days (or 10 x 1440 minutes) after\
        \ the initial send date.\n \n "
      operationId: "createResendToNonOpenersUsingPOST"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:send"
  /emails/activities/{campaign_activity_id}/non_opener_resends/{resend_request_id}:
    delete:
      tags:
      - "Email Campaigns"
      summary: "DELETE a Resend to Non Openers Activity"
      description: "Use this `DELETE` method to delete (unschedule) a resend to non\
        \ openers activity."
      operationId: "deleteResendToNonOpenersUsingDELETE"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:send"
  /emails/activities/{campaign_activity_id}/abtest:
    get:
      tags:
      - "Email Campaigns AB Tests"
      summary: "GET A/B Test Details for an Email Campaign Activity"
      description: "Use this method to get A/B test details for a primary email campaign\
        \ activity, such as the alternate email subject line, the contact test percentage\
        \ size, and the number of hours to wait to determine the winning subject line\
        \ to use. Currently, A/B tests support subject line only."
      operationId: "retrieveEmailCampaignABTestUsingGET"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:read"
    delete:
      tags:
      - "Email Campaigns AB Tests"
      summary: "DELETE an A/B Test for an Email Campaign Activity"
      description: "Deletes an A/B Test on an primary email campaign activity. You\
        \ can only delete A/B tests that have a `current_status` of `Draft`. Deleting\
        \ an A/B tests reverts the email campaign activity `type` from A/B Test (code=\
        \ `57`) back to NewsLetter (code= `10`). Constant Contact uses the original\
        \ subject line, rather than the alternate A/B test subject line, when an A/B\
        \ test is deleted."
      operationId: "deleteEmailCampaignABTestUsingDELETE"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "campaign:write"
  /reports/contact_reports/{contact_id}/activity_details:
    get:
      tags:
      - "Contacts Reporting"
      summary: "GET Contact Activity Details"
      description: "<p>Gets the tracking activity data for a given account and contact,\
        \ sorted in descending activity date order.</p><p>One or more tracking activity\
        \ types can be returned in a single request.</p><table><tr><td colspan='2'>Valid\
        \ tracking activity types</td></tr><tr><td><b>em_sends</b></td><td>Send activities</td></tr><tr><td><b>em_opens</b></td><td>Email\
        \ open tracking activities</td></tr><tr><td><b>em_clicks</b></td><td>Link\
        \ click-through tracking activities</td></tr><tr><td><b>em_bounces</b></td><td>Bounce\
        \ tracking activities</td></tr><tr><td><b>em_optouts</b></td><td>Opt-out tracking\
        \ activities</td></tr><tr><td><b>em_forwards</b></td><td>Forward to a friend\
        \ tracking activities</td></tr></table>"
      operationId: "getContactTracking"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/contact_reports/{contact_id}/open_and_click_rates:
    get:
      tags:
      - "Contacts Reporting"
      summary: "GET Average Open and Click Rates"
      description: "<p>Gets the average open and click rate for a given account and\
        \ contact.<p>Looks at all tracking activities for bulk emails from a given\
        \ contact over the given date range. Range cannot exceed 5 years.</p><p>Returns\
        \ the rates and the number of campaign activities that were included in the\
        \ calculation.</p><p>If no activities fall into the given date range, all\
        \ rates will return 0 and the number of included activities will be 0.</p>"
      operationId: "getContactOpenClickRate"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/contact_reports/{contact_id}/activity_summary:
    get:
      tags:
      - "Contacts Reporting"
      summary: "GET Contact Action Summary"
      description: "Get a list of the recent emails (aka, campaign activities) sent\
        \ to a specific contact and a summary of the actions the contact took on that\
        \ email for the most recent 200 campaigns."
      operationId: "getContactTrackingCount"
      security:
      - oauth2_implicit:
        - "contact_data"
      - oauth2_access_code:
        - "contact_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/links:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Links Report"
      description: "Use this method to return the number of unique contacts that clicked\
        \ each link in an email campaign activity and the type of action associated\
        \ with clicking each link. You can return reporting data for `primary_email`\
        \ and `resend` role email campaign activities. For more use case information,\
        \ see [Get an Email Links Report](/api_guide/email_links_report.html) in the\
        \ API guide."
      operationId: "getCampaignActivityLinkStats"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/sends:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Sends Report"
      description: "Use this method to get each contact that was sent a specific email\
        \ campaign activity. This sends report includes general contact data such\
        \ as the date and time that the email campaign activity was sent to a contact's\
        \ email address, the contact's first and last name, and unique ID. This report\
        \ lists the most recent activity first. For more use case information, see\
        \ [Get an Sends report for an Email Campaign Activity](/api_guide/email_summary_sends_report.html)\
        \ in the API guide."
      operationId: "getSends"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/opens:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Opens Report"
      description: "Use this method to get each time a contact opened a specific email\
        \ campaign activity. This report includes general contact information such\
        \ as the contact's email address and unique ID, the date and time they opened\
        \ the email campaign activity, and the type of device they used to open it.\
        \ This report lists the most recent activity first. For more use case information,\
        \ see [Get an Opens report for an Email Campaign Activity](/api_guide/email_summary_opens_report.html)\
        \ in the API guide."
      operationId: "getOpens"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/unique_opens:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Unique Opens Report"
      description: "Use this method to get a unique opens report that provides details\
        \ about the last time that each contact opened the specified email campaign\
        \ activity. This report includes general contact information such as the contact's\
        \ email address and unique ID, the date and time they opened the email campaign\
        \ activity, and the type of device they used to open it. This report lists\
        \ the most recent activity first. For more use case information, see [Get\
        \ an Unique Opens Report for an Email Campaign Activity](/api_guide/email_summary_unique_opens_report.html)\
        \ in the API guide."
      operationId: "getUniqueOpens"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/didnotopens:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Did Not Opens Report"
      description: "Use this method to get a report listing each contact that was\
        \ sent, but did not open the specified email campaign activity. This report\
        \ lists contact information such as the contact's email address and unique\
        \ ID, and the date and time that the email campaign activity was sent. This\
        \ report lists the most recent activity first. For more use case information,\
        \ see [Get a Did Not Opens Report for an Email Campaign Activity](/api_guide/email_summary_non_opens_report.html)\
        \ in the API guide."
      operationId: "getDidNotOpens"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/clicks:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Clicks Report"
      description: "Use this method to get each time a contact clicked a link, the\
        \ click date and time, and the device type they used. Use the `url_id` query\
        \ parameter to get a clicks report for a specific link URL. Clicks report\
        \ data is sorted with most recent activity listed first."
      operationId: "getClicks"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/forwards:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Forwards Report"
      description: "Use this method to get a report listing each time a contact forwarded\
        \ the email campaign activity using the forwarding link in the email footer.\
        \ The report includes general contact information, such as the contact's email\
        \ address and unique ID, and the date and time that the email campaign activity\
        \ was forwarded. Forwards report data is sorted with the most recent activity\
        \ listed first. For more use case information, see [Get an Email Forwards\
        \ Report](/api_guide/email_summary_forwards_report.html) in the API guide."
      operationId: "getForwards"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/optouts:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Opt-outs Report"
      description: "Use this method to get a report listing each contact that clicked\
        \ the unsubscribe link in the email campaign activity to opt-out from receiving\
        \ emails sent from your Constant Contact account. This report includes contact\
        \ information, such as the contact's email address, unique ID, and the opt-out\
        \ date and time. Opt-out report data is sorted with the most recent activity\
        \ listed first. For more use case information, see [Get an Email Opt-outs\
        \ Report](/api_guide/email_summary_optouts_report.html) in the API guide."
      operationId: "getOptouts"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/email_reports/{campaign_activity_id}/tracking/bounces:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Bounces Report"
      description: "Use this method to get a report listing contact bounce data for\
        \ the specified email campaign activity. This report lists the most recent\
        \ bounce data first and includes contact information, such as the contact's\
        \ email address, unique ID, and the email bounce date and time.\nUse the <code>bounce_code</code>\
        \ query parameter to limit the type of bounce data to return.\n\nFor more\
        \ use case information, see [Get a Bounces Report for an Email Campaign Activity](/api_guide/email_summary_bounces_report.html)\
        \ in the API guide."
      operationId: "getBounces"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/summary_reports/email_campaign_summaries:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Campaigns Summary Report"
      description: "Use this method to get aggregate email campaign statistics for\
        \ up to five hundred email campaigns. The response results include the total\
        \ number of times that each contact uniquely interacted with each tracked\
        \ campaign activity.\n\nResults are sorted in descending order by the date\
        \ that the email was last sent (<code>last_sent_date</code>). Use the <code>limit</code>\
        \ query parameter to limit the number of email campaign summary reports listed\
        \ on each page.\n\n\n\n For more use case information, see \"[Get an Email\
        \ Campaign Summary Report](/api_guide/email_bulk_campaign_summary_report.html)\""
      operationId: "getAllBulkEmailCampaignSummaries"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/stats/email_campaigns/{campaign_ids}:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Campaign Stats Report"
      description: "Use this method to get email campaign performance tracking statistics\
        \ for one or more campaigns, including the total number of times contacts\
        \ interacted with your campaigns and how.\n\nFor each `campaign_id`, this\
        \ method returns lists that include total counts (`stats`) for each type of\
        \ tracked email and relevant campaign-related percentages (`percents`). It\
        \ also returns the date and time at which the campaign stats were last refreshed.\n\
        If any specified `campaign_id` is invalid, a 404 error response is returned\
        \ for all campaigns."
      operationId: "getEmailSummary"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /reports/stats/email_campaign_activities/{campaign_activity_ids}:
    get:
      tags:
      - "Email Reporting"
      summary: "GET an Email Campaign Activity Stats Report"
      description: "Use this method to get performance tracking statistics for up\
        \ to ten email campaign activities. Statistics include the total number of\
        \ times contacts interacted with your campaigns and how.\n\nFor each `campaign_activity_id`,\
        \ this method returns the `campaign_id`, the total counts (`stats`) for each\
        \ type of tracked email activity, and the date and time that Constant Contact\
        \ last refreshed (`last_refresh_time`) the `stats`.\n\nWhen requesting statistics\
        \ for multiple email campaign activities, if one or more of the `campaign_activity_ids`\
        \ do not exist, were deleted, or do not have any stats associated with it,\
        \ the `campaign_activity_ids` and error details display under `errors`. If\
        \ any single specified `campaign_activity_id` is invalid (malformed), a 404\
        \ error response is returned for all campaign activities."
      operationId: "getEmailCampaignActivitySummary"
      security:
      - oauth2_implicit:
        - "campaign_data"
      - oauth2_access_code:
        - "campaign_data"
      - api_key: []
      x-authorization-privileges:
      - "ui:campaign:metrics"
  /partner/accounts:
    get:
      tags:
      - "Technology Partners"
      summary: "GET Partner Client Accounts"
      description: "Get all Constant Contact client accounts managed under your technology\
        \ partner account. Use the `limit` query parameter to set the number of accounts\
        \ to return on each results page. Use the `account_type` query parameter to\
        \ filter client account results by type: `all` (default), `managed`, or `unmanaged`.\n\
        Only technology partners can access partner endpoints and partner endpoints\
        \ cannot be tested using the API reference tester.\nFor more use case information,\
        \ see [Get all Partner Client Accounts](/api_guide/partners_accts_get.html)\
        \ in the API guide."
      operationId: "getPartnerSiteOwners"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
    post:
      tags:
      - "Technology Partners"
      summary: "POST (create) a Partner Client Account"
      description: "Use this POST method to create a new Constant Contact client account\
        \ under your partner account, set up the billing plan for the account, and\
        \ to add the new client to the default contact list.\n\nNewly created accounts\
        \ are free trials which give the user up to 60 days to try Constant Contact\
        \ before buying. Trial accounts have limits depending on the services that\
        \ are included.\n\nIf a field validation error occurs, a 400 response message\
        \ is returned.\n\nIf provisioning does not complete successfully due to unavailable\
        \ dependencies, such as database or dependent services, a 503 response message\
        \ is returned. By default, the client account provision data is stored and\
        \ processed when provisioning becomes available.\n\nSome client account features\
        \ will be supported in future releases, such as Single Sign On (SSO).\n\n\
        For more use case information, see [Create a new Partner Client Account](/api_guide/partners_accts_create.html)\
        \ in the API guide."
      operationId: "provision"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
  /partner/accounts/{encoded_account_id}/plan:
    get:
      tags:
      - "Technology Partners"
      summary: "GET Billing Plan Details for a Client Account"
      description: "Use this GET method to return billing plan details for a client's\
        \ Constant Contact account.\nOnly technology partners can access partner endpoints\
        \ and partner endpoints cannot be tested using the API reference tester.\n\
        For more use case information, see [Get Billing Plan Details for a Client\
        \ Account](/api_guide/partners_plans_get.html) in the API guide."
      operationId: "getPlan"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
    put:
      tags:
      - "Technology Partners"
      summary: "PUT (update) Billing Plan Details for a Client Account"
      description: "Use this PUT method to update the type of billing plan to assign\
        \ to the Constant Contact client account. The type of billing plan determines\
        \ which Constant Contact product features that the client account can access.\
        \ The billing plan type (`plan_type`) that you enter must already exist in\
        \ the plan group. Attempting to change to a plan that is currently not available\
        \ within your partner plan group results in a 400 error response code.\n\n\
        When you create a new client account, the `plan_type` defaults to `TRIAL`\
        \ and the `billing_day_of_month` defaults to `null`. The `billing_day_of_month`\
        \ property is required if a client account is not set up to use single billing.\
        \ You can change the day of month (`billing_day_of_month`) in which to bill\
        \ a client account only when changing the `plan_type` value from `TRIAL` to\
        \ a different `plan_type`, otherwise the `billing_day_of_month` value you\
        \ enter is ignored. You can choose to enter a specific day of the month or\
        \ accept the default value, which is the day on which the `plan_type` value\
        \ changes from a `TRIAL` plan to a different `plan_type`. Changing the `plan_type`\
        \ from `TRIAL` to another `plan_type` automatically changes the `billing_status`\
        \ from `Trial` to `Open`.\n\n\nOnly technology partners can access partner\
        \ endpoints and partner endpoints cannot be tested using the API reference\
        \ tester.\n\nFor more use case information, see [PUT Billing Plan Details\
        \ for a Client Account](/api_guide/partners_plans_update.html) in the API\
        \ guide."
      operationId: "setPlan"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
  /partner/accounts/{encoded_account_id}/status/cancel:
    put:
      tags:
      - "Technology Partners"
      summary: "PUT Cancel the Billing Plan for a Client Account"
      description: "Use this PUT method to cancel a client's Constant Contact account.\
        \ If the specified client account or technology partner account does not exist,\
        \ the system returns a 404 error response. If the client account exists under\
        \ a different technology partner account, the system returns a 400 error response.\n\
        \n\n  To get a list of all canceled client accounts (`\"billing_status\":\
        \ \"Canceled\"`), make a `GET` call to the `/partner/accounts` endpoint.\n\
        \n  Only technology partners can access partner endpoints and partner endpoints\
        \ cannot be tested using the API reference tester.\n\n  For more use case\
        \ information, see [Cancel the Billing Plan for a Client Account](/api_guide/partners_plans_cancel.html)\
        \ in the API guide.\""
      operationId: "cancelAccount"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
  /partner/webhooks/subscriptions:
    get:
      tags:
      - "Technology Partners Webhooks"
      summary: "GET a Collection of Webhook Topic Subscriptions"
      description: "Use this GET method to return a collection containing your application's\
        \ webhook subscriptions."
      operationId: "getWebhooksCollection"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
  /partner/webhooks/subscriptions/{topic_id}:
    get:
      tags:
      - "Technology Partners Webhooks"
      summary: "GET Webhook Topic Subscription"
      description: "Use this GET method to return subscription information for a certain\
        \ `topic_id`. Possible `topic_id` values include:\n\n  * `1` - Billing tier\
        \ upgrade.\n  * `2` - Billing tier downgrade.\n  * `3` - Account cancelled.\n\
        \  * `4` - Account disabled."
      operationId: "getWebhooksTopic"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
    put:
      tags:
      - "Technology Partners Webhooks"
      summary: "PUT Webhook Topic Subscription"
      description: "Use this PUT method to subscribe your application to a `topic_id`\
        \ or to update the callback URI for an existing subscription. Possible `topic_id`\
        \ values include:\n\n * `1` - Billing tier upgrade.\n * `2` - Billing tier\
        \ downgrade.\n * `3` - Account cancelled.\n * `4` - Account disabled.\n\n\
        After you subscribe your application, Constant Contact will automatically\
        \ start sending POST notifications for your chosen topic to your application's\
        \ callback URI. This is an example of the POST notification request body:\n\
        \n  ```\n  {\"url\":\"https://api.cc.email/v3/partner/accounts/a07e1my9tbw0/plan\"\
        ,\n  \"api_key\":\"90ed8738-5190-44a3-bc12-c172930db12c\",\n  \"event_type\"\
        :\"tier.increase\"}\n  ```\n</br>\nIf your application does not return a success\
        \ response after receiving a notification, Constant Contact will retry sending\
        \ the POST notification at 1 minute intervals for up to an hour."
      operationId: "putWebhooksTopic"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
    delete:
      tags:
      - "Technology Partners Webhooks"
      summary: "DELETE Webhook Topic Subscriptions"
      description: "Use this DELETE method to unsubscribe your application from notifications\
        \ on a certain `topic_id`. Possible `topic_id` values include:\n\n * `1` -\
        \ Billing tier upgrade.\n * `2` - Billing tier downgrade.\n * `3` - Account\
        \ cancelled.\n * `4` - Account disabled."
      operationId: "deleteWebhooksSubscriptions"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
  /partner/webhooks/subscriptions/{topic_id}/tests:
    post:
      tags:
      - "Technology Partners Webhooks"
      summary: "POST Test Send Webhook Notification"
      description: "Use this POST method to validate a webhook subscription by triggering\
        \ a test notification for your chosen webhook `topic_id`. Possible `topic_id`\
        \ values include:\n\n * `1` - Billing tier upgrade.\n * `2` - Billing tier\
        \ downgrade.\n * `3` - Account cancelled.\n * `4` - Account disabled.\n\n\
        After you successfully send this request, Constant Contact will automatically\
        \ send a POST notification to your chosen topic's callback URI with example\
        \ data."
      operationId: "testSendWebhooksTopic"
      security:
      - ctctPartnerAuthorizer: []
      - api_key: []
  /token_info:
    post:
      tags:
      - "Access Token Information"
      summary: "Access Token Information"
      description: "Use this POST method to retrieve the list of authorization scopes\
        \ associated with an OAuth2.0 access token.\n\nYou cannot retrieve authorization\
        \ information using expired access tokens.\n"
      operationId: "postAuthCode"
      security:
      - oauth2_implicit: []
      - oauth2_access_code: []
      - api_key: []
  /idfed:
    get:
      summary: "V3 Authorization service endpoint for OAuth 2.0 flows"
      description: "The authorization request is part of the OAuth 2.0 authorization\
        \ process for both the server and client flows."
      operationId: "getAuthCode"
securityDefinitions:
  oauth2_implicit:
    type: "oauth2"
    authorizationUrl: "https://api.cc.email/v3/idfed"
    flow: "implicit"
    scopes:
      contact_data: "Read or modify contact data."
      campaign_data: "Read or modify email campaign data."
      account_read: "Read account data."
      account_update: "Modify account data."
  oauth2_access_code:
    type: "oauth2"
    authorizationUrl: "https://api.cc.email/v3/idfed"
    tokenUrl: "https://idfed.constantcontact.com/as/token.oauth2"
    flow: "accessCode"
    scopes:
      contact_data: "Read or modify contact data."
      campaign_data: "Read or modify email campaign data."
      account_read: "Read account data."
      account_update: "Modify account data."
  ctctPartnerAuthorizer:
    type: "apiKey"
    name: "Unnamed"
    in: "header"
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"